### ISSUE TITLE
issue with chain.hhm file

### ISSUE THREAD

**Issue by Ravy-LFL** [YYingXia/LigBind#2]
Hi,

I am struggling with this issue ? the database and hhblits are installed, i can't find where this file is supposed to be generated ?
`Traceback (most recent call last):
  File "/PATH/prediction.py", line 445, in <module>
    hhm_fea = cal_HMM(query_path, sequence)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/PATH/prediction.py", line 70, in cal_HMM
    with open('{}/chain.hhm'.format(query_path), 'r') as fin:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
`

Thank you !

**Comment by YYingXia** [comment]
Hi, If the chain.hhm is generated correctly, it should be saved in the directory specified by "--querypath" that you set. :)
